okb: 
  nbins: 200 
  extractor_method: "orb"
  image_func: "diff"
  extractor_kwargs: 
    nfeatures: 500
    scaleFactor: 1.1 
    nlevels: 1

okbm:
  extractor_method: "orb"
  image_func: "diff"
  extractor_kwargs: 
    nfeatures: 2000
    scaleFactor: 1.1
    nlevels: 1
  cluster_kwargs: 
    min_samples: 10 
    max_eps: 10 
    eps: .5 
    xi: .5

blob: 
  image_func: "diff_sq"
  subtractive: False
  min_sigma: .45 
  max_sigma: 30
  num_sigma: 10 
  threshold: .4
  overlap: .5
  log_scale: False 
  exclude_border: False 
  n_neighbors: 3 
  dist_upper_bound: 5 
  angle_tolerance: 20   

jigsaw:
  # Parameters that seem to have the best results on Hirise pairs
  radius: 'yes'
  errorpropagation: 'yes'
  outlier_rejection: 'yes'
  point_longitude_sigma: 10 
  point_latitude_sigma: 10 
  point_radius_sigma: 2 
  maxits: 30
  sigma0: .1
  camsolve: "velocities"
  twist: "yes"
  overexisting: "yes"
  spsolve: "None"


 
